### ISSUE TITLE
Restructure repository

### ISSUE THREAD

**Issue by danlamanna** [danlamanna/joist#13]
Ideally the django portion of this repo will be structured such that the joist app (which will contain the s3 widget code) will be the top level concern. Within that there should be an example directory which contains a full fledged django project using the joist app.

**Comment by sgratzl** [comment]
what is the package name going to be? joist, if so we can rid of the s3widget package at all and just use the top level joist package

**Comment by brianhelba** [comment]
Repo filesystem layout
* `terraform`
* `joist` (Django app)
* `example` (Django working project)
* `js-joist` (published JS library)
* `example-client` (Vue implementation of a SPA using `js-joist`)
