### ISSUE TITLE
Package joist

### ISSUE THREAD

**Issue by danlamanna** [danlamanna/joist#14]
Have a Tox step to publish with Twine.

Ensure package.json is configured to publish to npm.

**Comment by sgratzl** [comment]
and automatically build the client code upon packaging

**Comment by sgratzl** [comment]
publish on tag via the CI

**Comment by brianhelba** [comment]
https://pypi.org/project/joist/

**Comment by sgratzl** [comment]
https://pypi.org/project/joist/ v0.0.2 is released. The CI is automatically triggered for the python code when one creates a Release here on Github
