### ISSUE TITLE
Add support for MinIO

### ISSUE THREAD

**Issue by danlamanna** [danlamanna/joist#19]
I'm not sure if we can make https://min.io/ support drop-in because there are apparently incompatibilities with django-storages and minio, see https://github.com/jschneier/django-storages/issues/362 for more detail.

**Comment by brianhelba** [comment]
Here is an example of some JavaScript which uploads directly to MinIO in a production environment. This was [adapted from `isic-archive`](https://github.com/ImageMarkup/isic-archive/blob/a080224256b0371e3864317c29278ee32a6a99d6/isic-archive-gui/src/Datasets/UploadBatch.vue#L138):
```
import S3 from 'aws-sdk/clients/s3';
// Fetch initUpload from Ajax
const s3Options = {
  apiVersion: '2006-03-01',
  accessKeyId: initUpload.accessKeyId,
  secretAccessKey: initUpload.secretAccessKey,
  sessionToken: initUpload.sessionToken,
};
if (process.env.NODE_ENV !== 'production') {
  Object.assign(s3Options, {
    endpoint: 'http://localhost:9000',
    s3ForcePathStyle: true,
    sessionToken: null,
  });
}
const s3 = new S3(s3Options);
await s3.upload({
  Bucket: initUpload.bucketName,
  Key: initUpload.objectKey,
  Body: this.zipFile,
});
```

**Comment by brianhelba** [comment]
Here is some server-side Python which configures Boto for use with MinIO in a development environment. This is [adapted from `isic-archive`](https://github.com/ImageMarkup/isic-archive/blob/a080224256b0371e3864317c29278ee32a6a99d6/isic_archive/utility/boto.py#L9):
```
from boto3.session import Session

s3Kwargs = {}
if developmentMode:
    s3Kwargs = {
        'endpoint_url': 'http://minio:9000',
        'aws_access_key_id': 'accesskey',
        'aws_secret_access_key': 'secretkey'
    }
# In production mode (always deployed to EC2), AWS Instance Profiles provide the access key ID and secret

session = Session()
s3 = session.client('s3', **s3Kwargs)
sts = session.client('sts')

if developmentMode:
    def mockStsAssumeRole(*args, **kwargs):
        return {
            'Credentials':
                {
                    'AccessKeyId': 'accesskey',
                    'SecretAccessKey': 'secretkey',
                    'SessionToken': 'baz'
                }
        }
    sts.assume_role = mockStsAssumeRole

# Use `s3` and `stsassume_role` as usual....
```

**Comment by brianhelba** [comment]
Here's an example Docker Compose config for running MinIO in development (with credentials compatible with the previous server code). This is adapted from `isic-archive`](https://github.com/ImageMarkup/isic-archive/blob/a080224256b0371e3864317c29278ee32a6a99d6/docker-compose.yml#L74).
```
minio:
  image: minio/minio:latest
  restart: always
  entrypoint: sh
  command: -c 'mkdir -p /minio-data/test-upload-bucket && /usr/bin/minio server /minio-data'
  environment:
    MINIO_ACCESS_KEY: accesskey
    MINIO_SECRET_KEY: secretkey
```
