### ISSUE TITLE
Do releases via CI.

### ISSUE THREAD

**Issue by sgratzl** [danlamanna/joist#32]
Depends on #22 and #14

**Comment by sgratzl** [comment]
there is an github action script in place (https://github.com/danlamanna/joist/blob/master/.github/workflows/pythonpublish.yml) but it requires secrets: 

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

I don't have admin rights to change settings so @danlamanna can you?

**Comment by danlamanna** [comment]
I added the secrets for pypi username and password.

**Comment by sgratzl** [comment]
see https://github.com/danlamanna/joist/commit/c0b7838fb04960c80d6ee871370fbcaf995b653d/checks?check_suite_id=322806341
